### ISSUE TITLE
Object reference not set to an instance of an object on empty Vorto

### ISSUE THREAD

**Issue by jbreuer** [mattbrailsford/umbraco-vorto#41]
I tried to upgrade the 1-1 multilingual example to Vorto 1.5.

When I have an empty value in Vorto I get an Object reference not set to an instance of an object.
![empty vorto](https://cloud.githubusercontent.com/assets/5444597/13454463/9f396a2a-e057-11e5-8e98-8ea39b397ee4.png)

The error happens with the following code:

`var urlSegment = this.GetVortoValue<string>("urlSegment", culture);`
https://github.com/jbreuer/1-1-multilingual-example/blob/master/Sources/Umbraco.Extensions/Models/UmbMaster.cs#L55

This is the stack trace:
   ```
at Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.DoInnerGetVortoValue[T](IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, T defaultValue)
   at Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.DoGetVortoValue[T](IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, T defaultValue)
   at Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.GetVortoValue[T](IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, T defaultValue, String fallbackCultureName)
   at Umbraco.Extensions.Models.UmbMaster.GetUrlSegment(String culture) in d:\data\inetpub\1-1-multilingual-example\Sources\Umbraco.Extensions\Models\UmbMaster.cs:line 55
   at Umbraco.Extensions.UrlProviders.MultilingualUrlProvider.<>c__DisplayClass3.<GetUrl>b__0() in d:\data\inetpub\1-1-multilingual-example\Sources\Umbraco.Extensions\UrlProviders\MultilingualUrlProvider.cs:line 80
   at Umbraco.Core.Cache.CacheProviderExtensions.<>c__DisplayClass9`1.<GetCacheItem>b__8()
   at Umbraco.Core.Cache.DictionaryCacheProviderBase.<>c__DisplayClass1.<GetSafeLazy>b__0()
```
Do you need any more info?

**Comment by alecrt** [comment]
I can confirm the problem. 
In 1.5 GetVortoValue has changed its behaviour when the value of the specified culture in not set. Now throws an exception.

**Comment by mattbrailsford** [comment]
@alecrt which line specifically are you referring to that has changed?

**Comment by alecrt** [comment]
Sorry @mattbrailsford didn't look at the source code still.

The exception thrown is "The given key was not present in the dictionary" and happens when a specific culture is passed as cultureName parameter in DoInnerGetVortoValue method.

So my guess is that something goes wrong here:

var bestMatchCultureName = vortoModel.FindBestMatchCulture(cultureName);
var value = vortoModel.Values[bestMatchCultureName];

**Comment by mattbrailsford** [comment]
I've added some additional null checking to that area in DoInnerGetVorotValue (it should have actually been the same checks that occur in HasVortoValue but for some reason they were less restrictive) so hopefully this should fix it. There is a new release on the build server if you guys fancy giving it a try and letting me know if this fixes it for you?

https://ci.appveyor.com/project/mattbrailsford/umbraco-vorto/build/1.5.1.36/artifacts

Cheers

Matt

**Comment by jbreuer** [comment]
I have upgraded to Our.Umbraco.Vorto.1.5.1-alpha-000036.nupkg and now it's fixed. Thanks for the quick response.

**Comment by mattbrailsford** [comment]
Awesome! Thanks for reporting the issue.

**Comment by alecrt** [comment]
Thanks!

**Comment by jbreuer** [comment]
I just upgraded from Vorto 1.5.3 to 1.6.0 and I get the same error again. Is it possible this somehow got reverted in the latest version?

**Comment by jbreuer** [comment]
I have downgraded back to Vorto 1.5.3 and the error is gone. Reopend the issue.
