### ISSUE TITLE
Doesn't work on Media Type in Umbraco 7.5

### ISSUE THREAD

**Issue by jbreuer** [mattbrailsford/umbraco-vorto#60]
When I try to use Vorto on a Media Type in Umbraco 7.5 I get the following error when I try to save:

```
Received an error from the server
An error occured

The given key was not present in the dictionary.

EXCEPTION DETAILS

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
STACKTRACE

at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Umbraco.Core.Persistence.Repositories.MediaRepository.PersistUpdatedItem(IMedia entity)
   at Umbraco.Core.Cache.DefaultRepositoryCachePolicy`2.CreateOrUpdate(TEntity entity, Action`1 persistMethod)
   at Umbraco.Core.Persistence.Repositories.RepositoryBase`2.PersistUpdatedItem(IEntity entity)
   at Umbraco.Core.Persistence.UnitOfWork.PetaPocoUnitOfWork.Commit(Action`1 transactionCompleting)
   at Umbraco.Core.Services.MediaService.Umbraco.Core.Services.IMediaServiceOperations.Save(IMedia media, Int32 userId, Boolean raiseEvents)
   at Umbraco.Web.Editors.MediaController.PostSave(MediaItemSave contentItem)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
```

Topic: https://our.umbraco.org/projects/backoffice-extensions/vorto/bugs-feedback-suggestions/54332-using-vorto-in-the-media-section#comment-254117

**Comment by jbreuer** [comment]
Also reported it as a bug for Umbraco: http://issues.umbraco.org/issue/U4-8907

**Comment by jbreuer** [comment]
It seems this is a bug in Umbraco 7.5: http://issues.umbraco.org/issue/U4-8923

**Comment by mattbrailsford** [comment]
Closing as core issue
